#!/usr/bin/env bash
# Copyright (C) 2026 Diderde
# SPDX-License-Identifier: GPL-3.0-only
#
# 04 - 收尾：定版本串 -> 增量重链 -> 剥符号 -> 换进仓库 -> 跑许可审计。
#
# 为什么定版本串放在最后：源码来自 tarball（无 .git），version.sh 无法
# git describe，FFMPEG_VERSION 会退化成 "8.0.git"；而 03 的 make 又会重新生成
# libavutil/ffversion.h 把它覆盖回去。所以顺序必须是
#   02 构建 -> 03 归一中缀 -> 04 定版本 + 剥符号 + 收件
#
# 用法（在 MSYS2 MINGW64 shell 里）：
#   MSYSTEM=MINGW64 WORK=/d/path/to/work bash tools/ffmpeg-build/04-finalize.sh
#
# 环境变量：
#   WORK                    构建工作目录（默认：当前目录下的 ffmpeg-build）
#   REPO                    仓库根（默认：本脚本上两级目录）
#   FFMPEG_PREFIX           中性前缀（须与 03 一致，默认 /ffbuild/ffmpeg-lgpl）
#   FFMPEG_VERSION_STRING   要写入的版本串（默认 N-125829-gfe953596e9）
#   JOBS                    并行度（默认：nproc）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${REPO:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
WORK="${WORK:-$PWD/ffmpeg-build}"
SRC="$(head -1 "$WORK/source-info.txt")"
FPREFIX="${FFMPEG_PREFIX:-/ffbuild/ffmpeg-lgpl}"
DEST="$REPO/app/resources/ffmpeg/bin"
EXTRA="${MSYS2_ROOT:-/mingw64}/bin"
JOBS="${JOBS:-$(nproc)}"
VER="${FFMPEG_VERSION_STRING:-N-125829-gfe953596e9}"

BINARIES="libavcodec/avcodec-63.dll libavformat/avformat-63.dll libavutil/avutil-61.dll
libavfilter/avfilter-12.dll libavdevice/avdevice-63.dll
libswresample/swresample-7.dll libswscale/swscale-10.dll
ffmpeg.exe ffprobe.exe"

cd "$SRC"

echo "=== 参数 ==="
echo "  REPO = $REPO"
echo "  WORK = $WORK"
echo "  OUT  = $OUT"
echo "  DEST = $DEST"
echo "  VER  = $VER"
echo "  中性前缀 = $FPREFIX"

echo
echo "=== 1. 取旧前缀（由 03 留下的备份推导，不写死本机路径）==="
OLD_PREFIX=""
if [ -f config.h.bak-prefix ]; then
  OLD_PREFIX="$(grep -oE '^#define FFMPEG_CONFIGURATION "--prefix=[^ ]+' config.h.bak-prefix | head -1 | sed 's/.*--prefix=//')"
fi
echo "  旧前缀 = ${OLD_PREFIX:-（无备份，跳过旧前缀复核）}"

echo
echo "=== 2. 定版本串 ==="
grep FFMPEG_VERSION libavutil/ffversion.h
CURRENT="$(grep -oE '"[^"]+"' libavutil/ffversion.h | tr -d '"')"

if [ "$CURRENT" = "$VER" ]; then
  echo "  已是 $VER，跳过重写与重链"
else
  echo "  重写为 $VER"
  cat > libavutil/ffversion.h <<EOF
/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "$VER"
#endif /* AVUTIL_FFVERSION_H */
EOF
  grep FFMPEG_VERSION libavutil/ffversion.h

  touch libavutil/version.c libavcodec/version.c libavformat/version.c \
        libavfilter/version.c libavdevice/version.c libswresample/version.c \
        libswscale/version.c
  echo "  只重编 version.c 并重链（-o 防止级联）"
  make -o config.h -o ffbuild/config.mak -j"$JOBS" 2>&1 | tail -14
fi

echo
echo "=== 3. 剥符号（增量重链不会自动剥，须显式做）==="
for f in $BINARIES; do
  [ -f "$f" ] || continue
  before=$(stat -c %s "$f")
  strip -s "$f" 2>/dev/null || strip "$f" 2>/dev/null || true
  after=$(stat -c %s "$f")
  printf '  %-34s %10d -> %10d B\n' "$f" "$before" "$after"
done

echo
echo "=== 4. 复核：无开发机路径 ==="
# 探针 = 03 记下的旧前缀；不写死任何本机路径
LEFT=0
for f in $BINARIES; do
  if [ -n "$OLD_PREFIX" ] && grep -q -- "$OLD_PREFIX" "$f" 2>/dev/null; then
    echo "  *** $f 含旧前缀 ***"; LEFT=$((LEFT+1))
  fi
done
echo "  残留: $LEFT 个"
[ "$LEFT" -eq 0 ] || exit 1

echo
echo "=== 5. 换进仓库 ==="
mkdir -p "$DEST"
# 防护门（AGENTS.md §4.2）：清空重建前先探测体量、确认目标在仓库内
DEST_REAL="$(cd "$DEST" && pwd)"
REPO_REAL="$(cd "$REPO" && pwd)"
case "$DEST_REAL" in
  "$REPO_REAL"/*) : ;;
  *) echo "  *** 拒绝清理：$DEST_REAL 不在仓库内（$REPO_REAL）***"; exit 1 ;;
esac
OLD_COUNT=$(find "$DEST" -maxdepth 1 -type f | wc -l)
OLD_SIZE=$(du -sh "$DEST" 2>/dev/null | cut -f1)
echo "  待清理：$OLD_COUNT 个文件 / $OLD_SIZE"
echo "  将写入：$(echo "$BINARIES" | wc -w) 个 FFmpeg 产物 + 4 个运行时 DLL"
find "$DEST" -maxdepth 1 -type f -delete

for f in $BINARIES; do
  cp -f "$f" "$DEST/"; echo "  换入 $(basename "$f")"
done
for n in libgcc_s_seh-1.dll libwinpthread-1.dll libmp3lame-0.dll libopus-0.dll; do
  [ -f "$EXTRA/$n" ] && { cp -f "$EXTRA/$n" "$DEST/"; echo "  随附 $n"; } || echo "  *** 缺 $n ***"
done

echo
echo "=== 6. 终检 ==="
ls -la "$DEST"
echo "  合计: $(du -sh "$DEST" | cut -f1)"
"$DEST/ffmpeg.exe" -hide_banner -version 2>&1 | head -2
echo -n "  configure 前缀: "
"$DEST/ffmpeg.exe" -hide_banner -buildconf 2>&1 | grep -o -- '--prefix=[^ ]*' | head -1
"$DEST/ffmpeg.exe" -hide_banner -L 2>&1 | grep -i "lesser general public" | head -1

echo
echo "=== 7. 许可审计（必须 PASS）==="
cd "$REPO"
if [ -x .venv/Scripts/python.exe ]; then PY=.venv/Scripts/python.exe; else PY=python; fi
"$PY" tools/audit_ffmpeg_license.py

echo
echo "=== 8. 许可文本校验 ==="
"$PY" tools/verify_ffmpeg_licenses.py

echo
echo "RESULT: PASS"
